apiVersion: v1
kind: Service
metadata:
  name: student-service
  labels:
    app: student-platform
spec:
  type: NodePort
  selector:
    app: student-platform
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30090
      protocol: TCP
